//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKTX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DangKyNoiTru
    {
        public string MaSV { get; set; }
        public System.DateTime NgayGui { get; set; }
        public string MaPhong { get; set; }
        public string TrangThai { get; set; }
        public string GhiChu { get; set; }
    
        public virtual SinhVien SinhVien { get; set; }
        public virtual Phong Phong { get; set; }
    }
}
