//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKTX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HinhPhatQuaCacLanTaiPham
    {
        public string MaViPham { get; set; }
        public int LanTaiPham { get; set; }
        public string HinhPhat { get; set; }
    }
}
