//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKTX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HopDong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HopDong()
        {
            this.DangKyLuuTruHes = new HashSet<DangKyLuuTruHe>();
        }
    
        public string MaHopDong { get; set; }
        public string MaSV { get; set; }
        public string NguoiTao { get; set; }
        public System.DateTime NgayTao { get; set; }
        public System.DateTime NgayBatDau { get; set; }
        public System.DateTime NgayKetThuc { get; set; }
        public string TrangThai { get; set; }
        public bool DaThanhToan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DangKyLuuTruHe> DangKyLuuTruHes { get; set; }
        public virtual SinhVien SinhVien { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
