//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKTX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhaiBaoHuHong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhaiBaoHuHong()
        {
            this.XuLyKhaiBaoHuHongs = new HashSet<XuLyKhaiBaoHuHong>();
        }
    
        public string MaKhaiBao { get; set; }
        public System.DateTime NgayYeuCau { get; set; }
        public string MaPhong { get; set; }
        public string MaThietBi { get; set; }
        public int TongSoLuong { get; set; }
        public bool DaXuLy { get; set; }
        public string NguoiXuLy { get; set; }
    
        public virtual Phong Phong { get; set; }
        public virtual ThietBi ThietBi { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XuLyKhaiBaoHuHong> XuLyKhaiBaoHuHongs { get; set; }
    }
}
