//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKTX.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class KyTucXaEntities : DbContext
    {
        public KyTucXaEntities()
            : base("name=KyTucXaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChiTietHoaDon> ChiTietHoaDons { get; set; }
        public virtual DbSet<DangKyLuuTruHe> DangKyLuuTruHes { get; set; }
        public virtual DbSet<DangKyNoiTru> DangKyNoiTrus { get; set; }
        public virtual DbSet<DichVu> DichVus { get; set; }
        public virtual DbSet<DichVuPhongCoChiSo> DichVuPhongCoChiSoes { get; set; }
        public virtual DbSet<HoaDon> HoaDons { get; set; }
        public virtual DbSet<HopDong> HopDongs { get; set; }
        public virtual DbSet<KhaiBaoHuHong> KhaiBaoHuHongs { get; set; }
        public virtual DbSet<Khu> Khus { get; set; }
        public virtual DbSet<LoaiThongBao> LoaiThongBaos { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<Phong> Phongs { get; set; }
        public virtual DbSet<SinhVien> SinhViens { get; set; }
        public virtual DbSet<SinhVienViPham> SinhVienViPhams { get; set; }
        public virtual DbSet<SuDungDichVuDon> SuDungDichVuDons { get; set; }
        public virtual DbSet<Tang> Tangs { get; set; }
        public virtual DbSet<ThietBi> ThietBis { get; set; }
        public virtual DbSet<ThongBao> ThongBaos { get; set; }
        public virtual DbSet<ViPham> ViPhams { get; set; }
        public virtual DbSet<XuLyKhaiBaoHuHong> XuLyKhaiBaoHuHongs { get; set; }
        public virtual DbSet<HinhPhat> HinhPhats { get; set; }
        public virtual DbSet<HinhPhatQuaCacLanTaiPham> HinhPhatQuaCacLanTaiPhams { get; set; }
        public virtual DbSet<ThongKeDangKyLuTru> ThongKeDangKyLuTrus { get; set; }
        public virtual DbSet<ThongKeDichVuDonMoiPhong> ThongKeDichVuDonMoiPhongs { get; set; }
    
        public virtual int CapNhatSoLuongKhaiBaoHuHong(string maThietBi, string maPhong, Nullable<int> soLuong)
        {
            var maThietBiParameter = maThietBi != null ?
                new ObjectParameter("maThietBi", maThietBi) :
                new ObjectParameter("maThietBi", typeof(string));
    
            var maPhongParameter = maPhong != null ?
                new ObjectParameter("maPhong", maPhong) :
                new ObjectParameter("maPhong", typeof(string));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("soLuong", soLuong) :
                new ObjectParameter("soLuong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CapNhatSoLuongKhaiBaoHuHong", maThietBiParameter, maPhongParameter, soLuongParameter);
        }
    
        public virtual int TaoDangKyNoiTru(string maSV, string maPhong)
        {
            var maSVParameter = maSV != null ?
                new ObjectParameter("maSV", maSV) :
                new ObjectParameter("maSV", typeof(string));
    
            var maPhongParameter = maPhong != null ?
                new ObjectParameter("maPhong", maPhong) :
                new ObjectParameter("maPhong", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TaoDangKyNoiTru", maSVParameter, maPhongParameter);
        }
    
        public virtual int TaoHopDong(string maSV, string tenDN)
        {
            var maSVParameter = maSV != null ?
                new ObjectParameter("maSV", maSV) :
                new ObjectParameter("maSV", typeof(string));
    
            var tenDNParameter = tenDN != null ?
                new ObjectParameter("tenDN", tenDN) :
                new ObjectParameter("tenDN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TaoHopDong", maSVParameter, tenDNParameter);
        }
    }
}
