//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKTX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Phong()
        {
            this.DangKyNoiTrus = new HashSet<DangKyNoiTru>();
            this.DichVuPhongCoChiSoes = new HashSet<DichVuPhongCoChiSo>();
            this.HoaDons = new HashSet<HoaDon>();
            this.KhaiBaoHuHongs = new HashSet<KhaiBaoHuHong>();
            this.SinhViens = new HashSet<SinhVien>();
        }
    
        public string Ma { get; set; }
        public string Ten { get; set; }
        public string MaTang { get; set; }
        public bool DangSuaChua { get; set; }
        public int SoLuongTrong { get; set; }
        public string TruongPhong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DangKyNoiTru> DangKyNoiTrus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DichVuPhongCoChiSo> DichVuPhongCoChiSoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhaiBaoHuHong> KhaiBaoHuHongs { get; set; }
        public virtual Tang Tang { get; set; }
        public virtual SinhVien SinhVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SinhVien> SinhViens { get; set; }
    }
}
