//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKTX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuDungDichVuDon
    {
        public string MaSV { get; set; }
        public string MaDichVu { get; set; }
        public bool DangSuDung { get; set; }
    
        public virtual DichVu DichVu { get; set; }
        public virtual SinhVien SinhVien { get; set; }
    }
}
