//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKTX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongKeDichVuDonMoiPhong
    {
        public string MaPhong { get; set; }
        public string MaDichVu { get; set; }
        public string TenDichVu { get; set; }
        public int GiaHienTai { get; set; }
        public Nullable<int> SoLuong { get; set; }
    }
}
