//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKTX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YeuCauSuaChua
    {
        public string MaThietBi { get; set; }
        public string MaSV { get; set; }
        public System.DateTime NgayYeuCau { get; set; }
        public int SoLuong { get; set; }
        public string TrangThai { get; set; }
    
        public virtual SinhVien SinhVien { get; set; }
        public virtual ThietBi ThietBi { get; set; }
    }
}
